require 'bundler'
Bundler.require 
require 'jq'

require 'sinatra/reloader' if development?

require 'rss'

get '/' do
  haml :index
end

get '/feed' do
  jq = JQ(RestClient.get(params[:url]))
  result = []
  jq.search(params[:ids]).each do |id|
    result.push({id: id})
  end
  jq.search(params[:titles]).each_with_index do |title, idx|
    result[idx][:title] = title
  end

  rss = RSS::Maker.make('1.0') do |maker|
    maker.channel.about = ''
    maker.channel.title = params[:title]
    maker.channel.description = 'Generated by JSON to Feed'
    maker.channel.link = params[:url]

    result.each do |x|
      item = maker.items.new_item
      item.link = "#{params[:urlbase]}#{x[:id]}"
      item.title = x[:title]
      item.description = ''
    end
  end
  content_type :xml
  rss.to_s
end
